OUTPUT_DIR := ./bin

all:

	gcc -o $(OUTPUT_DIR)/client_crea client_crea.c -Wall \
	gcc -o $(OUTPUT_DIR)/client_joiner client_joiner.c -Wall

clean:

	rm /tmp/info_*
	rm /tmp/crea_to_joiner
	rm /tmp/joiner_to_crea
